apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reverse-ip-chart.fullname" . }}
  labels:
    {{ include "reverse-ip-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "reverse-ip-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "reverse-ip-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: reverse-ip-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}

