apiVersion: v1
kind: Service
metadata:
  name: {{ include "reverse-ip-chart.fullname" . }}
  labels:
    {{ include "reverse-ip-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    {{ include "reverse-ip-chart.selectorLabels" . | nindent 4 }}

