replicaCount: 1

image:
  repository: gcr.io/reverse-ip-51286/reverse-ip-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

resources: {}

ingress:
  enabled: false

autoscaling:
  enabled: false

