name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reverse-ip-app:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3.sh | bash

      - name: Deploy to Kubernetes
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm upgrade --install reverse-ip-app ./reverse-ip-chart
